# Voor debugging en cache-busting
ENV CACHE_BREAKER=2025-07-09

FROM node:22-bookworm-slim

RUN mkdir /opt/flowfuse-device
RUN npm install -g @flowfuse/device-agent

# COPY device.yml /opt/flowfuse-device/device.yml

COPY entrypoint.sh /usr/src/entrypoint.sh

ENTRYPOINT ["/usr/src/entrypoint.sh"]

CMD ["flowfuse-device-agent"]

