FROM balenalib/raspberrypi4-64-node:22-bookworm-run

RUN mkdir /opt/flowfuse-device
RUN npm install -g @flowfuse/device-agent

# COPY device.yml /opt/flowfuse-device/device.yml

COPY entrypoint.sh /usr/src/entrypoint.sh

ENTRYPOINT ["/usr/src/entrypoint.sh"]

CMD ["flowfuse-device-agent"]

